version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: f1_postgres
    environment:
      POSTGRES_DB: f1_web
      POSTGRES_USER: f1_user
      POSTGRES_PASSWORD: f1_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - f1_network

  redis:
    image: redis:7-alpine
    container_name: f1_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - f1_network

  # 可选：用于开发时的数据库管理工具
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: f1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@f1web.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - f1_network

  # 可选：Redis管理工具
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: f1_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - f1_network

volumes:
  postgres_data:
  redis_data:

networks:
  f1_network:
    driver: bridge
