services:
  # 主Web服务 - 免费版
  - type: web
    name: f1-web-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --only=main"
    startCommand: "poetry run python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: DATABASE_URL
        fromDatabase:
          name: f1-web-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: f1-web-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

  # Redis缓存服务 - 免费版
  - type: redis
    name: f1-web-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: f1-web-db
    databaseName: f1_web
    user: f1_user
    plan: free
