"""重新设计数据模型以匹配FastF1实际数据结构

Revision ID: 1d9fd4ddb73e
Revises: 
Create Date: 2025-06-21 20:11:38.762401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9fd4ddb73e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuit_id', sa.String(length=50), nullable=False),
    sa.Column('circuit_url', sa.String(length=500), nullable=True),
    sa.Column('circuit_name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('lap_record', sa.String(length=50), nullable=True),
    sa.Column('lap_record_driver', sa.String(length=100), nullable=True),
    sa.Column('lap_record_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('circuit_id')
    )
    op.create_index(op.f('ix_circuits_circuit_id'), 'circuits', ['circuit_id'], unique=False)
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('driver_code', sa.String(length=10), nullable=True),
    sa.Column('driver_url', sa.String(length=500), nullable=True),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('driver_nationality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_drivers_driver_id'), 'drivers', ['driver_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=True)
    op.create_table('constructors',
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('constructor_url', sa.String(length=500), nullable=True),
    sa.Column('constructor_name', sa.String(length=200), nullable=False),
    sa.Column('constructor_nationality', sa.String(length=100), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('base', sa.String(length=200), nullable=True),
    sa.Column('team_chief', sa.String(length=100), nullable=True),
    sa.Column('technical_chief', sa.String(length=100), nullable=True),
    sa.Column('power_unit', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('championships', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('podiums', sa.Integer(), nullable=False),
    sa.Column('poles', sa.Integer(), nullable=False),
    sa.Column('fastest_laps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('constructor_id')
    )
    op.create_index(op.f('ix_constructors_constructor_id'), 'constructors', ['constructor_id'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.String(length=50), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('official_event_name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_format', sa.String(length=50), nullable=True),
    sa.Column('session1', sa.String(length=100), nullable=True),
    sa.Column('session1_date', sa.DateTime(), nullable=True),
    sa.Column('session2', sa.String(length=100), nullable=True),
    sa.Column('session2_date', sa.DateTime(), nullable=True),
    sa.Column('session3', sa.String(length=100), nullable=True),
    sa.Column('session3_date', sa.DateTime(), nullable=True),
    sa.Column('session4', sa.String(length=100), nullable=True),
    sa.Column('session4_date', sa.DateTime(), nullable=True),
    sa.Column('session5', sa.String(length=100), nullable=True),
    sa.Column('session5_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.circuit_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_table('constructor_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constructor_standing_season', 'constructor_standings', ['season_id'], unique=False)
    op.create_index('idx_constructor_standing_season_constructor', 'constructor_standings', ['season_id', 'constructor_id'], unique=False)
    op.create_index(op.f('ix_constructor_standings_id'), 'constructor_standings', ['id'], unique=False)
    op.create_table('driver_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_seasons_id'), 'driver_seasons', ['id'], unique=False)
    op.create_table('driver_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_driver_standing_season', 'driver_standings', ['season_id'], unique=False)
    op.create_index('idx_driver_standing_season_constructor', 'driver_standings', ['season_id', 'constructor_id'], unique=False)
    op.create_index('idx_driver_standing_season_driver', 'driver_standings', ['season_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_driver_standings_id'), 'driver_standings', ['id'], unique=False)
    op.create_table('qualifying_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('q1_time', sa.String(length=100), nullable=True),
    sa.Column('q2_time', sa.String(length=100), nullable=True),
    sa.Column('q3_time', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifying_results_id'), 'qualifying_results', ['id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=10), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_race_time_millis', sa.BigInteger(), nullable=True),
    sa.Column('total_race_time', sa.String(length=100), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_number', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_time', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_table('sprint_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('constructor_id', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=10), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_time', sa.String(length=100), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_number', sa.Integer(), nullable=True),
    sa.Column('total_race_time', sa.String(length=100), nullable=True),
    sa.Column('total_race_time_millis', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprint_results_id'), 'sprint_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprint_results_id'), table_name='sprint_results')
    op.drop_table('sprint_results')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_qualifying_results_id'), table_name='qualifying_results')
    op.drop_table('qualifying_results')
    op.drop_index(op.f('ix_driver_standings_id'), table_name='driver_standings')
    op.drop_index('idx_driver_standing_season_driver', table_name='driver_standings')
    op.drop_index('idx_driver_standing_season_constructor', table_name='driver_standings')
    op.drop_index('idx_driver_standing_season', table_name='driver_standings')
    op.drop_table('driver_standings')
    op.drop_index(op.f('ix_driver_seasons_id'), table_name='driver_seasons')
    op.drop_table('driver_seasons')
    op.drop_index(op.f('ix_constructor_standings_id'), table_name='constructor_standings')
    op.drop_index('idx_constructor_standing_season_constructor', table_name='constructor_standings')
    op.drop_index('idx_constructor_standing_season', table_name='constructor_standings')
    op.drop_table('constructor_standings')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_constructors_constructor_id'), table_name='constructors')
    op.drop_table('constructors')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_drivers_driver_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_circuits_circuit_id'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
