"""修复模型关系

Revision ID: 2ea9a05225fa
Revises: 1d9fd4ddb73e
Create Date: 2025-06-21 20:24:50.543337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea9a05225fa'
down_revision: Union[str, Sequence[str], None] = '1d9fd4ddb73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'event_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'event_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
