"""添加is_sprint字段到Race模型

Revision ID: c8785911c0f4
Revises: 2ea9a05225fa
Create Date: 2025-06-21 23:13:11.073738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8785911c0f4'
down_revision: Union[str, Sequence[str], None] = '2ea9a05225fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('is_sprint', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'is_sprint')
    # ### end Alembic commands ###
