"""添加F1赛道详细信息字段

Revision ID: f17a20b245aa
Revises: f0fa87eb95f6
Create Date: 2025-07-10 19:38:31.387912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17a20b245aa'
down_revision: Union[str, Sequence[str], None] = 'f0fa87eb95f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('first_grand_prix', sa.Integer(), nullable=True))
    op.add_column('circuits', sa.Column('typical_lap_count', sa.Integer(), nullable=True))
    op.add_column('circuits', sa.Column('race_distance', sa.Float(), nullable=True))
    op.add_column('circuits', sa.Column('circuit_layout_image_url', sa.String(length=500), nullable=True))
    op.add_column('circuits', sa.Column('circuit_layout_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuits', 'circuit_layout_image_path')
    op.drop_column('circuits', 'circuit_layout_image_url')
    op.drop_column('circuits', 'race_distance')
    op.drop_column('circuits', 'typical_lap_count')
    op.drop_column('circuits', 'first_grand_prix')
    # ### end Alembic commands ###
