export const countryCodeMap: Record<string, string> = {
  // Country names to 3-letter code
  Australia: "aus",
  Austria: "aut",
  Azerbaijan: "aze",
  Bahrain: "brn",
  Belgium: "bel",
  Brazil: "bra",
  Canada: "can",
  China: "chn",
  France: "fra",
  Germany: "ger",
  Hungary: "hun",
  Italy: "ita",
  Japan: "jpn",
  Mexico: "mex",
  Monaco: "mon",
  Netherlands: "ned",
  Qatar: "qat",
  "Saudi Arabia": "ksa",
  Singapore: "sgp",
  Spain: "esp",
  "United Arab Emirates": "uae",
  "United Kingdom": "gbr",
  "United States": "usa",

  // Nationality to 3-letter code
  Argentine: "arg",
  Australian: "aus",
  Austrian: "aut",
  Belgian: "bel",
  Brazilian: "bra",
  British: "gbr",
  Canadian: "can",
  Chinese: "chn",
  Danish: "den",
  Dutch: "ned",
  Finnish: "fin",
  French: "fra",
  German: "ger",
  Hungarian: "hun",
  Indian: "ind",
  Italian: "ita",
  Japanese: "jpn",
  Mexican: "mex",
  Monegasque: "mon",
  "New Zealander": "nzl",
  Polish: "pol",
  Portuguese: "por",
  Russian: "rus",
  Spanish: "esp",
  Swedish: "swe",
  Swiss: "sui",
  Thai: "tha",
  American: "usa",

  // Common shorthands/aliases
  UK: "gbr",
  USA: "usa",

  // Special Locations to Country mapping
  Sakhir: "brn", // Testing
  Imola: "ita",
  Mugello: "ita",
  "Las Vegas": "usa",
  Miami: "usa",
  Austin: "usa", // COTA
};
