export const nationalityToFlagCode: Record<string, string> = {
  American: "US",
  Argentine: "AR",
  Australian: "AU",
  Austrian: "AT",
  Belgian: "BE",
  Brazilian: "BR",
  British: "GB",
  Canadian: "CA",
  Chinese: "CN",
  Danish: "DK",
  Dutch: "NL",
  Finnish: "FI",
  French: "FR",
  German: "DE",
  Hungarian: "HU",
  Indian: "IN",
  Italian: "IT",
  Japanese: "JP",
  Mexican: "MX",
  Monegasque: "MC",
  "New Zealander": "NZ",
  Polish: "PL",
  Portuguese: "PT",
  Russian: "RU",
  Spanish: "ES",
  Swedish: "SE",
  Swiss: "CH",
  Thai: "TH",
};
